In [1]:
import pandas as pd
import math as m
import json
import numpy as np

user = 1
index_user = user - 1
negOne = -1
k = 4

data = pd.read_csv("data.csv", index_col = 0)
print(data.iloc[index_user])
data

 Movie 1    -1
 Movie 2     4
 Movie 3     1
 Movie 4     5
 Movie 5    -1
 Movie 6    -1
 Movie 7    -1
 Movie 8     1
 Movie 9     3
 Movie 10   -1
 Movie 11    5
 Movie 12    5
 Movie 13    1
 Movie 14    3
 Movie 15    3
 Movie 16    3
 Movie 17   -1
 Movie 18    4
 Movie 19    2
 Movie 20    2
 Movie 21    2
 Movie 22    4
 Movie 23   -1
 Movie 24   -1
 Movie 25    3
 Movie 26    4
 Movie 27   -1
 Movie 28    2
 Movie 29    4
 Movie 30    1
Name: User 1, dtype: int64

,Movie 1,Movie 2,Movie 3,Movie 4,Movie 5,Movie 6,Movie 7,Movie 8,Movie 9,Movie 10,...,Movie 21,Movie 22,Movie 23,Movie 24,Movie 25,Movie 26,Movie 27,Movie 28,Movie 29,Movie 30
User 1,-1,4,1,5,-1,-1,-1,1,3,-1,...,2,4,-1,-1,3,4,-1,2,4,1
User 2,4,5,2,3,3,4,-1,5,3,2,...,-1,2,-1,3,1,5,-1,5,2,2
User 3,4,2,5,4,1,5,-1,3,5,2,...,4,-1,5,4,5,1,2,1,-1,3
User 4,5,-1,2,-1,-1,2,4,3,2,3,...,-1,2,2,2,2,5,3,2,5,5
User 5,4,3,3,3,5,3,3,4,5,2,...,4,5,2,-1,3,5,1,-1,5,-1
User 6,2,-1,3,3,3,3,4,2,-1,1,...,5,-1,1,3,-1,4,4,5,1,2
User 7,4,1,4,4,1,4,5,2,2,-1,...,2,5,1,3,4,-1,4,3,1,4
User 8,-1,5,5,3,3,3,3,3,1,2,...,-1,3,1,3,2,1,4,-1,1,3
User 9,1,2,3,1,5,3,3,1,2,5,...,3,2,3,-1,1,4,3,1,5,3
User 10,5,-1,1,-1,3,3,4,1,1,2,...,4,1,4,1,4,5,2,3,-1,1
User 11,-1,5,-1,1,5,2,4,2,4,-1,...,4,-1,3,4,1,2,4,2,5,1
User 12,5,4,4,-1,3,-1,5,5,5,3,...,1,4,1,5,3,5,4,3,5,5
User 13,1,1,4,5,4,3,5,5,5,4,...,2,3,2,-1,4,3,-1,5,5,4
User 14,3,5,4,-1,1,2,4,-1,-1,4,...,4,1,5,4,1,-1,3,1,5,3
User 15,3,5,3,4,4,-1,4,4,2,1,...,2,2,5,1,3,4,-1,-1,5,4
User 16,3,3,5,3,2,2,5,-1,4,4,...,1,3,4,-1,4,4,4,2,4,4
User 17,1,1,-1,-1,4,4,-1,-1,1,1,...,4,2,4,2,2,-1,5,4,5,3
User 18,4,3,3,2,1,5,3,4,5,2,...,-1,4,5,2,1,1,2,1,-1,4
User 19,4,3,5,5,4,4,-1,-1,4,4,...,2,3,1,2,-1,2,5,1,2,1
User 20,2,-1,2,5,-1,-1,1,-1,2,-1,...,-1,2,4,1,-1,2,2,3,3,4
User 21,-1,2,1,2,3,5,4,1,2,3,...,-1,5,1,2,5,5,4,4,2,-1
User 22,2,4,4,-1,4,-1,4,5,5,4,...,4,5,1,-1,-1,5,2,2,5,-1
User 23,5,1,-1,5,5,-1,-1,5,-1,3,...,-1,-1,3,1,5,-1,1,5,3,5
User 24,5,4,2,-1,2,1,3,2,1,2,...,4,2,2,1,3,2,5,2,5,4
User 25,3,1,-1,4,2,-1,4,1,5,3,...,2,-1,5,5,2,-1,1,3,1,2
User 26,1,5,-1,3,-1,2,4,-1,4,2,...,5,3,1,5,2,-1,2,2,4,-1
User 27,4,4,3,-1,4,5,3,4,3,-1,...,-1,3,4,3,-1,3,2,3,2,5
User 28,-1,-1,4,2,3,2,1,4,-1,1,...,1,3,2,1,4,3,2,4,2,1
User 29,3,2,4,2,2,2,4,1,3,3,...,3,-1,3,5,5,5,4,-1,5,-1
User 30,2,3,5,4,1,3,3,2,3,1,...,4,5,1,1,4,5,3,1,3,5
User 31,3,5,4,5,1,3,3,3,4,1,...,5,4,4,3,5,2,2,4,4,-1
User 32,5,4,5,4,1,5,5,4,4,-1,...,5,2,-1,2,3,2,1,3,1,-1
User 33,5,3,4,4,2,1,3,1,3,3,...,2,1,5,5,2,-1,2,1,4,2
User 34,-1,5,-1,-1,1,-1,5,1,1,5,...,3,3,4,-1,3,1,5,2,2,5
User 35,4,-1,5,4,2,2,3,1,1,5,...,5,1,2,1,5,5,1,-1,5,5
User 36,3,2,-1,5,5,1,5,2,1,5,...,-1,2,4,3,4,5,2,1,3,4
User 37,-1,4,-1,3,1,4,5,4,3,3,...,3,3,-1,5,-1,5,2,3,5,-1
User 38,3,-1,1,4,2,3,4,-1,5,3,...,5,4,3,-1,1,4,3,-1,-1,4
User 39,1,-1,5,-1,1,2,3,-1,2,5,...,4,2,5,2,3,1,2,1,2,1
User 40,-1,1,1,1,1,-1,4,1,-1,3,...,3,5,4,2,3,4,5,5,3,2

Функция подсчёта среднего у user:

In [2]:
def MeanUser(data, index):
    count = 0
    sum = 0
    for item in data.iloc[index]:
        if(item != negOne):
            sum += item
            count += 1
    return sum / count

Функция, которая ищет k user'ов, у которых есть оценка для фильма:

In [3]:
def FindUsers(data, index_film, k):
    ind_users = []
    for i in range(1, k + 1):
        if(data.iloc[i][index_film] != negOne):
            ind_users.append(i)
    return ind_users

Функция расчёта метрики косинуса sim:

In [4]:
def sim(data, index1, index2):
    col1 = data.iloc[index1]
    col2 = data.iloc[index2]
    count = len(col1)
    sumUp = 0
    sumDown1 = 0
    sumDown2 = 0
    for i in range(0, count):
        if((col1[i] != negOne) & (col2[i] != negOne)):
            sumUp = sumUp + col1[i] * col2[i]
            sumDown1 = sumDown1 + col1[i] * col1[i]
            sumDown2 = sumDown2 + col2[i] * col2[i]
    return sumUp / ((sumDown1 ** .5) * (sumDown2 ** .5))

Задание 1:

Высчитаем метрики для пар - наш пользователь со всеми остальными:

In [5]:
l = []
for i in range(0, len(data)):  
    l.append(sim(data, index_user, i))

Отсортируем пользователей по метрике:

In [6]:
dataCopy = data.copy()
for i in range(1, len(dataCopy)):
    for j in range(0, len(dataCopy) - i):
        if(l[j] < l[j + 1]):
            a, b = dataCopy.iloc[j, :].copy(), dataCopy.iloc[j+1, :].copy()
            dataCopy.iloc[j, :], dataCopy.iloc[j+1, :] = b, a
            t = l[j]
            l[j] = l[j+1]
            l[j+1] = t

Высчитаем оценки:

In [7]:
dictMarks = {}
meanRightUser = MeanUser(dataCopy, 0)
for i in range(0, len(dataCopy.columns)):
    if(dataCopy.iloc[0][i] == negOne):
        index_users = FindUsers(dataCopy, i, k)
        sumSim = 0
        sumSimAbs = 0
        for item in index_users:
            #tempSim = sim(data, 0, index_users[j])
            tempSim = l[item]
            sumSim = sumSim + tempSim * (dataCopy.iloc[item][i] - MeanUser(dataCopy, item))
            sumSimAbs = sumSimAbs + m.fabs(tempSim)
        dictMarks.update({"movie " + str(i+1) : round(meanRightUser + (sumSim / sumSimAbs), 3)})
dictMarks

{'movie 1': 3.968,
 'movie 5': 2.712,
 'movie 6': 3.093,
 'movie 7': 3.714,
 'movie 10': 2.228,
 'movie 17': 1.458,
 'movie 23': 2.712,
 'movie 24': 2.975,
 'movie 27': 3.096}

Задание 2:

In [8]:
dataDays = pd.read_csv("context_day.csv", index_col = 0).T
dataPlaces = pd.read_csv("context_place.csv", index_col = 0).T

weeknd1 = "Sat"
weeknd2 = "Sun"
home = "h"

Функция подсчёта средней оценки у фильма:

In [9]:
def MeanFilm(data, index_film):
    data = data.T
    sum = 0
    count = 0
    for mark in data.iloc[index_film]:
        if(mark != negOne):
            sum += mark
            count +=1
    return sum / count

Функция подсчёта процента посмотревших на выходных:

In [10]:
def PercWeekends(data, index_film):
    watchedOnWeekend = 0
    watchedTotal = 0
    for mark in data.iloc[index_film]:
        mark = mark.strip(' ')
        if(mark != str(negOne)):
            watchedTotal += 1
            if((mark == weeknd1) | (mark == weeknd2)):
                watchedOnWeekend += 1
    return watchedOnWeekend / watchedTotal

Функция подсчёта процента посмотревших дома:

In [11]:
def PercHome(data, index_film):
    watchedHome = 0
    watchedTotal = 0
    for mark in data.iloc[index_film]:
        mark = mark.strip(' ')
        if(mark != str(negOne)):
            watchedTotal += 1
            if(mark == home):
                watchedHome += 1
    return watchedHome / watchedTotal

Функция поиска фильмов:

In [12]:
def FindFilms(data, index_user):
    l = []
    d = data.iloc[index_user]
    for i in range(0, len(d)):
        if(d[i] == negOne):
            l.append(i)
    return l

Расчёт оценки - ср. знач. * % посмотревших в выходные * % посмотревших дома:

Причём оценки будут лежать в диапазоне от 0 до 5: 2 * 0.0% * 0.0% - худший вариант и 5 * 1.0% * 1.0% - лучший

In [13]:
def BestFilm(d, dDays, dPlaces, index_user):
    l = []
    films = FindFilms(d, index_user)
    for index in films:
        l.append(MeanFilm(d, index) * PercWeekends(dDays, index) * PercHome(dPlaces, index))  
    print(l)
    film = 'Movie ' + str(int(films[l.index(max(l))]) + 1)
    return film

bestFilm = BestFilm(data, dataDays, dataPlaces, index_user)
print(bestFilm)

[0.279296875, 0.44999571330589844, 0.12486992715920915, 0.2261856299613271, 0.3109607164665174, 0.26825179088553575, 0.27520576131687247, 0.33984375, 0.23842592592592593]
Movie 5

In [14]:
answer = {"user": user, "1": dictMarks, "2": bestFilm}
print(answer)

{'user': 1, '1': {'movie 1': 3.968, 'movie 5': 2.712, 'movie 6': 3.093, 'movie 7': 3.714, 'movie 10': 2.228, 'movie 17': 1.458, 'movie 23': 2.712, 'movie 24': 2.975, 'movie 27': 3.096}, '2': 'Movie 5'}

In [15]:
with open('answer.json', 'w', encoding = 'utf-8') as f:
    json.dump(answer, f, ensure_ascii = False, indent = 4)

Задание 3.2:

In [16]:
from SPARQLWrapper import SPARQLWrapper, JSON
import pandas as pd
import requests

In [17]:
films = pd.read_csv("movie_names.csv", index_col=0)

In [18]:
recFilm = films.loc[bestFilm]
recFilm

Film     12 Angry Men
Name: Movie 5, dtype: object

In [19]:
API_ENDPOINT = "https://www.wikidata.org/w/api.php"

params = {
    'action' : 'wbsearchentities',
    'format' : 'json',
    'language' : 'en',
    'search': recFilm
}

res = requests.get(API_ENDPOINT, params = params)
IdFilm = res.json()['search'][0]['id']
print(IdFilm)

Q2345

In [20]:
sparql = SPARQLWrapper("https://query.wikidata.org/sparql")

sparql_query = """

SELECT DISTINCT ?filmLabel ?oscarLabel
WHERE {
  {
    SELECT ?yearOfMyFilm
    WHERE {
      wd:""" + IdFilm + """ wdt:P577 ?creationDate.
      BIND(MIN(YEAR(?creationDate)) AS ?yearOfMyFilm).
    }
  }
  ?oscar wdt:P31 wd:Q19020.
  ?oscarStat ps:P166 ?oscar;
             pq:P585 ?oscarDate.
  ?film wdt:P31 wd:Q11424;
        p:P166 ?oscarStat.          
  FILTER((YEAR(?oscarDate)) = ?yearOfMyFilm)
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }
 }

 
"""

sparql.setQuery(sparql_query)
sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results_df = pd.json_normalize(results['results']['bindings'])
results_df[['filmLabel.value', 'oscarLabel.value']]

               filmLabel.value                              oscarLabel.value
0            Nights of Cabiria  Academy Award for Best Foreign Language Film
1            Albert Schweitzer    Academy Award for Best Documentary Feature
2  Around the World in 80 Days                Academy Award for Best Picture